// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal.proto

package au_com_kieltyka_james_internal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InternalDataParameters struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalDataParameters) Reset()         { *m = InternalDataParameters{} }
func (m *InternalDataParameters) String() string { return proto.CompactTextString(m) }
func (*InternalDataParameters) ProtoMessage()    {}
func (*InternalDataParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_abc6d160079eceb2, []int{0}
}
func (m *InternalDataParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalDataParameters.Unmarshal(m, b)
}
func (m *InternalDataParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalDataParameters.Marshal(b, m, deterministic)
}
func (dst *InternalDataParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalDataParameters.Merge(dst, src)
}
func (m *InternalDataParameters) XXX_Size() int {
	return xxx_messageInfo_InternalDataParameters.Size(m)
}
func (m *InternalDataParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalDataParameters.DiscardUnknown(m)
}

var xxx_messageInfo_InternalDataParameters proto.InternalMessageInfo

func (m *InternalDataParameters) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InternalDataParameters) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type InternalData struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalData) Reset()         { *m = InternalData{} }
func (m *InternalData) String() string { return proto.CompactTextString(m) }
func (*InternalData) ProtoMessage()    {}
func (*InternalData) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_abc6d160079eceb2, []int{1}
}
func (m *InternalData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalData.Unmarshal(m, b)
}
func (m *InternalData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalData.Marshal(b, m, deterministic)
}
func (dst *InternalData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalData.Merge(dst, src)
}
func (m *InternalData) XXX_Size() int {
	return xxx_messageInfo_InternalData.Size(m)
}
func (m *InternalData) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalData.DiscardUnknown(m)
}

var xxx_messageInfo_InternalData proto.InternalMessageInfo

func (m *InternalData) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*InternalDataParameters)(nil), "au.com.kieltyka.james.internal.InternalDataParameters")
	proto.RegisterType((*InternalData)(nil), "au.com.kieltyka.james.internal.InternalData")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InternalServiceClient is the client API for InternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InternalServiceClient interface {
	GetInternalData(ctx context.Context, in *InternalDataParameters, opts ...grpc.CallOption) (*InternalData, error)
}

type internalServiceClient struct {
	cc *grpc.ClientConn
}

func NewInternalServiceClient(cc *grpc.ClientConn) InternalServiceClient {
	return &internalServiceClient{cc}
}

func (c *internalServiceClient) GetInternalData(ctx context.Context, in *InternalDataParameters, opts ...grpc.CallOption) (*InternalData, error) {
	out := new(InternalData)
	err := c.cc.Invoke(ctx, "/au.com.kieltyka.james.internal.InternalService/GetInternalData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalServiceServer is the server API for InternalService service.
type InternalServiceServer interface {
	GetInternalData(context.Context, *InternalDataParameters) (*InternalData, error)
}

func RegisterInternalServiceServer(s *grpc.Server, srv InternalServiceServer) {
	s.RegisterService(&_InternalService_serviceDesc, srv)
}

func _InternalService_GetInternalData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalDataParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GetInternalData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/au.com.kieltyka.james.internal.InternalService/GetInternalData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GetInternalData(ctx, req.(*InternalDataParameters))
	}
	return interceptor(ctx, in, info, handler)
}

var _InternalService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "au.com.kieltyka.james.internal.InternalService",
	HandlerType: (*InternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInternalData",
			Handler:    _InternalService_GetInternalData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal.proto",
}

func init() { proto.RegisterFile("internal.proto", fileDescriptor_internal_abc6d160079eceb2) }

var fileDescriptor_internal_abc6d160079eceb2 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x4b, 0x2c, 0xd5, 0x4b,
	0xce, 0xcf, 0xd5, 0xcb, 0xce, 0x4c, 0xcd, 0x29, 0xa9, 0xcc, 0x4e, 0xd4, 0xcb, 0x4a, 0xcc, 0x4d,
	0x2d, 0xd6, 0x83, 0xa9, 0x52, 0xb2, 0xe1, 0x12, 0xf3, 0x84, 0xb2, 0x5d, 0x12, 0x4b, 0x12, 0x03,
	0x12, 0x8b, 0x12, 0x73, 0x53, 0x4b, 0x52, 0x8b, 0x8a, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x98, 0x32, 0x53, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73,
	0x53, 0x25, 0x98, 0xc0, 0x22, 0x60, 0xb6, 0x92, 0x06, 0x17, 0x0f, 0xb2, 0x6e, 0x21, 0x09, 0x2e,
	0xf6, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0xa8, 0x46, 0x18, 0xd7, 0xa8, 0x87, 0x91, 0x8b,
	0x1f, 0xa6, 0x34, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xa8, 0x92, 0x8b, 0xdf, 0x3d, 0xb5,
	0x04, 0xc5, 0x00, 0x33, 0x3d, 0xfc, 0xee, 0xd5, 0xc3, 0xee, 0x58, 0x29, 0x1d, 0x52, 0xf4, 0x29,
	0x31, 0x24, 0xb1, 0x81, 0x43, 0xc7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x5b, 0xcc, 0x6b,
	0x2f, 0x01, 0x00, 0x00,
}
